spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/gft-parking?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
